language: android
sudo: required
Jdk: oraclejdk8

env:
  global:
    - ADB_INSTALL_TIMEOUT=5 # minutes
    - ANDROID_API_LEVEL=22
    - EMULATOR_API_LEVEL=21
    - ANDROID_ABI=armeabi-v7a
    - ANDROID_TAG=google_apis

#So that cache isnt always uploaded
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

android:
  components:
    - tools
    - tools
    - android-28
    - android-22
    - platform-tools
    - build-tools-28.0.3
    - build-tools-29.0.0
    - extra
    # To run emulator during your tests
    - sys-img-x86-android-28
    - sys-img-armeabi-v7a-android-22
    - sys-img-armeabi-v7a-addon-google_apis-google-$ANDROID_API_LEVEL
    - sys-img-armeabi-v7a-addon-google_apis-google-$EMULATOR_API_LEVEL

  licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

before_install:
  - chmod +x gradlew
  - yes | sdkmanager "build-tools;28.0.3"
  - yes | sdkmanager "platforms;android-28"

before_script:
  #- echo no | android create avd --force -n test -t "android-"$EMULATOR_API_LEVEL --abi $ANDROID_ABI --tag $ANDROID_TAG
  - echo no | android create avd --force -n test -t android-22 --abi armeabi-v7a -c 32M
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &


script:
  - ./gradlew clean build connectedCheck -PdisablePreDex --stacktrace #--scan
  - ./gradlew -Dscan=true build

after_success:
  - ./gradlew jacocoTestReport coveralls
